[book]
authors = ["Marc-André Lureau", "Zeeshan Ali Khan"]
language = "en"
multilingual = false
src = "src"
title = "zbus: D-Bus for Rust made easy"

[rust]
edition = "2018"

[output.html]
default-theme = "Rust"
curly-quotes = true
git-repository-url = "https://github.com/dbus2/zbus"
git-repository-icon = "fa-github"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
